import os

OFFERS_PORT = os.getenv('OFFERS_PORT')
OFFERS_POSTGRES_DB = os.getenv('OFFERS_POSTGRES_DB')
OFFERS_POSTGRES_USER = os.getenv('OFFERS_POSTGRES_USER')
OFFERS_POSTGRES_PASSWORD = os.getenv('OFFERS_POSTGRES_PASSWORD')
OFFERS_POSTGRES_HOST = os.getenv('OFFERS_POSTGRES_HOST')
OFFERS_POSTGRES_PORT = os.getenv('OFFERS_POSTGRES_PORT')
