import os

USERS_PORT = os.getenv('USERS_PORT')
USERS_POSTGRES_DB = os.getenv('USERS_POSTGRES_DB')
USERS_POSTGRES_USER = os.getenv('USERS_POSTGRES_USER')
USERS_POSTGRES_PASSWORD = os.getenv('USERS_POSTGRES_PASSWORD')
USERS_POSTGRES_HOST = os.getenv('USERS_POSTGRES_HOST')
USERS_POSTGRES_PORT = os.getenv('USERS_POSTGRES_PORT')

OFFERS_HOST = os.getenv('OFFERS_HOST', 'localhost')
OFFERS_PORT = os.getenv('OFFERS_PORT')

SECRET_KEY = os.getenv('SECRET_KEY')
